import TypeIt from "typeit";

document.addEventListener("DOMContentLoaded", () => {
    new TypeIt("#typeIt", {
      lifeLike: true,
      startDelay: 1000,
      loop: true,
      cursorChar: " |",
    })
      .pause(3000)
      .delete()
      .pause(500)
      .type("students.")
      .pause(1000)
      .move(-9)
      .type("<i>naïve<i> ")
      .pause(2000)
      .delete()
      .type("a conference for ")
      .pause(1500)
      .move(9)
      .delete()
      .pause(500)
      .type("our Asian stereotypes.")
      .pause(2500)
      .delete(18)
      .type("immigrant stories.")
      .pause(2500)
      .delete(18)
      .type("generational trauma.")
      .pause(4000)
      .delete()
      .pause(500)
      .type("the bamboo ceiling.")
      .pause(2000)
      .delete()
      .type("future leaders.")
      .pause(2000)
      .delete()
      .type("our GPAs.")
      .pause(2500)
      .delete()
      .type("aspiring creatives.")
      .pause(2000)
      .delete()
      .type("TA's.")
      .pause(2000)
      .delete()
      .type("the sum of our meal points.")
      .pause(2000)
      .delete()
      .type("young activists.")
      .pause(2000)
      .delete()
      .type("our childhood instruments.")
      .pause(2000)
      .delete()
      .type("conditioned perfectionists.")
      .pause(5000)
      .delete()
      .type("professors.")
      .pause(2000)
      .delete()
      .type("change-makers.")
      .pause(2000)
      .delete()
      .type("another free food event.")
      .pause(2000)
      .delete()
      .type("<span class='tiny'>but, we do have free food.</span>")
      .pause(5000)
      .delete()
      .type("<span class='tiny'>seriously. so much food. pls help.</span>")
      .pause(1000)
      .delete()
      .go();
  });